name: supabase_auth_app
description: Flutter app with Supabase authentication, Riverpod & GoRouter.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
